### ISSUE TITLE
Chains with a dash ('-') in the name won't work

### ISSUE THREAD

**Issue by kerryamatthews** [matwei/perl-App-Iptables2Dot#2] opened 2017-04-06 22:31 UTC
The "dot" command gives a syntax error when parsing the generated "*.dot" file.

**Comment by ghost** [comment] 2018-12-25 19:07
I confirm the issue. The error I get from Graphviz dot is `Warning: <stdin>: syntax error in line 5 near '-'`, where line 5 looks like `CNI-HOSTPORT-MASQ [shape=none,margin=0...`. Enclosing into `" "` solves the problem.

**Comment by matwei** [comment] 2021-04-13 12:28
I added the option --use-numbered-nodes in v0.3.0.
This will replace the chains with node0, node1, .. and might help according to https://stackoverflow.com/a/57896404

**Comment by Chaz6** [comment] 2021-04-13 14:58
I have this problem too. I tried using --user-numbered-nodes but this caused a new problem. This is the resulting output:-

```
[..]
    node39:R4:e -> RETURN:w;
    node40:R4:e -> RETURN:w;
    node41:R0:e -> RETURN:w;
    node42:R0:e -> :name:w; <-- line 181
    node42:R1:e -> :name:w;
    node42:R2:e -> :name:w;
    node42:R3:e -> :name:w;
    node42:R4:e -> :name:w;
    node42:R5:e -> :name:w;
    node43:R0:e -> :name:w;
    node44:R0:e -> :name:w;
    node44:R1:e -> :name:w;
    node44:R2:e -> :name:w;
    node44:R3:e -> :name:w;
    node44:R4:e -> :name:w;
    node44:R5:e -> :name:w;
    node45:R0:e -> :name:w;
    node46:R0:e -> node49:name:w;
    node46:R1:e -> node48:name:w;
    node46:R2:e -> node47:name:w;
[..]
```

running `dot` gives `Error: iptables.dot: syntax error in line 181 near ':'` The command used was `iptables2dot --add-optdef=dst-type=s --add-optdef=helper=s --add-optdef=mss=s --use-numbered-nodes ./iptables.txt > iptables.dot && dot ./iptables.dot > iptables.png` and the iptables output is [iptables.txt](https://github.com/matwei/perl-App-Iptables2Dot/files/6304649/iptables.txt)

**Comment by matwei** [comment] 2021-04-13 16:16
Thanks for the `iptables-save` output. I'll look into this.

**Comment by matwei** [comment] 2021-04-13 18:40
@Chaz6 can you try out commit [f6f08b0](https://github.com/matwei/perl-App-Iptables2Dot/commit/f6f08b064bd8168541c868f703d0aa2501ada0b8)? It should work like this:

    perl -Ilib bin/iptables2dot --use-numbered-nodes iptables.txt
or

    perl -Ilib bin/iptables2dot --noshowrules --use-numbered-nodes iptables.txt

If this solves your problem, I'll add tests for regressions and release it as v0.3.1.

**Comment by matwei** [comment] 2021-11-30 16:10
At least v0.3.2 doesn't have the problem described by @Chaz6, therefore I'm closing this issue.

**Closed as completed by matwei** 2021-11-30 16:10 UTC
